# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13b29a4ae9217145fb526249d27bb8ad033fdafff41487a39141901b9768aedc66fbe1556f3ca7fd8fb6323a7dd3646ed748dc044a96d21a559f33a8d93c7314

test:
  secret_key_base: 2dea399f8c7a599af95b14976de6c8bad91ef1227fd9d5be55e4fcd7bee630bcd978eb5e00f487163b2f4c058d3e5f9571e61eb2ed17ac11d771d1f47242fbe8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
